# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_hud.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_hud(object):
    def setupUi(self, hud):
        hud.setObjectName("hud")
        hud.resize(400, 519)
        self.frameButtons = QtWidgets.QFrame(hud)
        self.frameButtons.setGeometry(QtCore.QRect(10, 10, 51, 261))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameButtons.sizePolicy().hasHeightForWidth())
        self.frameButtons.setSizePolicy(sizePolicy)
        self.frameButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameButtons.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameButtons.setObjectName("frameButtons")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameButtons)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolButtonLayers = QtWidgets.QToolButton(self.frameButtons)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/legend.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonLayers.setIcon(icon)
        self.toolButtonLayers.setIconSize(QtCore.QSize(24, 24))
        self.toolButtonLayers.setCheckable(False)
        self.toolButtonLayers.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButtonLayers.setObjectName("toolButtonLayers")
        self.verticalLayout.addWidget(self.toolButtonLayers)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolButtonIsActive = QtWidgets.QToolButton(self.frameButtons)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/toolButtonIsActive.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonIsActive.setIcon(icon1)
        self.toolButtonIsActive.setIconSize(QtCore.QSize(22, 22))
        self.toolButtonIsActive.setCheckable(True)
        self.toolButtonIsActive.setObjectName("toolButtonIsActive")
        self.horizontalLayout_2.addWidget(self.toolButtonIsActive)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sliderZoomlevels = QtWidgets.QSlider(self.frameButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderZoomlevels.sizePolicy().hasHeightForWidth())
        self.sliderZoomlevels.setSizePolicy(sizePolicy)
        self.sliderZoomlevels.setMaximum(25)
        self.sliderZoomlevels.setTracking(False)
        self.sliderZoomlevels.setOrientation(QtCore.Qt.Vertical)
        self.sliderZoomlevels.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.sliderZoomlevels.setTickInterval(1)
        self.sliderZoomlevels.setObjectName("sliderZoomlevels")
        self.horizontalLayout_4.addWidget(self.sliderZoomlevels)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.toolButtonTMS = QtWidgets.QToolButton(hud)
        self.toolButtonTMS.setGeometry(QtCore.QRect(70, 20, 39, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/toolButtonTMS.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonTMS.setIcon(icon2)
        self.toolButtonTMS.setIconSize(QtCore.QSize(24, 24))
        self.toolButtonTMS.setCheckable(True)
        self.toolButtonTMS.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButtonTMS.setObjectName("toolButtonTMS")
        self.frameButtons.raise_()
        self.toolButtonTMS.raise_()

        self.retranslateUi(hud)
        QtCore.QMetaObject.connectSlotsByName(hud)

    def retranslateUi(self, hud):
        _translate = QtCore.QCoreApplication.translate
        hud.setWindowTitle(_translate("hud", "Form"))
        self.frameButtons.setAccessibleName(_translate("hud", "frameMainButtons"))
        self.toolButtonLayers.setToolTip(_translate("hud", "Add Layers"))
        self.toolButtonLayers.setStatusTip(_translate("hud", "Add Layers"))
        self.toolButtonLayers.setText(_translate("hud", "≡"))
        self.toolButtonIsActive.setToolTip(_translate("hud", "Enable/Disable Scale Levels"))
        self.toolButtonIsActive.setStatusTip(_translate("hud", "Enable/Disable Scale Levels"))
        self.toolButtonIsActive.setText(_translate("hud", "o"))
        self.sliderZoomlevels.setToolTip(_translate("hud", "Zoomlevel"))
        self.toolButtonTMS.setToolTip(_translate("hud", "Enable/Disable Scale Levels"))
        self.toolButtonTMS.setStatusTip(_translate("hud", "Enable/Disable Scale Levels"))
        self.toolButtonTMS.setText(_translate("hud", "≡"))

from . import resources_rc
