# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tilemapscalelevelswidget.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TileMapScaleLevelsDockWidget(object):
    def setupUi(self, TileMapScaleLevelsDockWidget):
        TileMapScaleLevelsDockWidget.setObjectName("TileMapScaleLevelsDockWidget")
        TileMapScaleLevelsDockWidget.resize(474, 246)
        TileMapScaleLevelsDockWidget.setMinimumSize(QtCore.QSize(159, 161))
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 432, 161))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolButtonIsActive = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/toolButtonIsActive.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonIsActive.setIcon(icon)
        self.toolButtonIsActive.setIconSize(QtCore.QSize(22, 22))
        self.toolButtonIsActive.setCheckable(True)
        self.toolButtonIsActive.setObjectName("toolButtonIsActive")
        self.horizontalLayout_2.addWidget(self.toolButtonIsActive)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.toolButtonLayers = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/legend.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonLayers.setIcon(icon1)
        self.toolButtonLayers.setIconSize(QtCore.QSize(24, 24))
        self.toolButtonLayers.setCheckable(False)
        self.toolButtonLayers.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButtonLayers.setObjectName("toolButtonLayers")
        self.horizontalLayout_2.addWidget(self.toolButtonLayers)
        self.buttonLoadUserDataset = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/edit-add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonLoadUserDataset.setIcon(icon2)
        self.buttonLoadUserDataset.setIconSize(QtCore.QSize(22, 22))
        self.buttonLoadUserDataset.setObjectName("buttonLoadUserDataset")
        self.horizontalLayout_2.addWidget(self.buttonLoadUserDataset)
        self.buttonLoadRefreshUserDatasets = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonLoadRefreshUserDatasets.setIcon(icon3)
        self.buttonLoadRefreshUserDatasets.setIconSize(QtCore.QSize(22, 22))
        self.buttonLoadRefreshUserDatasets.setObjectName("buttonLoadRefreshUserDatasets")
        self.horizontalLayout_2.addWidget(self.buttonLoadRefreshUserDatasets)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.buttonInfo = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/help-hint.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonInfo.setIcon(icon4)
        self.buttonInfo.setIconSize(QtCore.QSize(22, 22))
        self.buttonInfo.setObjectName("buttonInfo")
        self.horizontalLayout_2.addWidget(self.buttonInfo)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.groupBoxZoomlevels = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxZoomlevels.setObjectName("groupBoxZoomlevels")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBoxZoomlevels)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.sliderZoomlevels = QtWidgets.QSlider(self.groupBoxZoomlevels)
        self.sliderZoomlevels.setToolTip("")
        self.sliderZoomlevels.setStatusTip("")
        self.sliderZoomlevels.setMaximum(25)
        self.sliderZoomlevels.setSliderPosition(0)
        self.sliderZoomlevels.setTracking(False)
        self.sliderZoomlevels.setOrientation(QtCore.Qt.Horizontal)
        self.sliderZoomlevels.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.sliderZoomlevels.setTickInterval(1)
        self.sliderZoomlevels.setObjectName("sliderZoomlevels")
        self.verticalLayout.addWidget(self.sliderZoomlevels)
        self.spinBoxZoomlevels = QtWidgets.QSpinBox(self.groupBoxZoomlevels)
        self.spinBoxZoomlevels.setKeyboardTracking(False)
        self.spinBoxZoomlevels.setMaximum(25)
        self.spinBoxZoomlevels.setObjectName("spinBoxZoomlevels")
        self.verticalLayout.addWidget(self.spinBoxZoomlevels)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_7.addWidget(self.groupBoxZoomlevels)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab, "")
        self.OptionsTab = QtWidgets.QWidget()
        self.OptionsTab.setObjectName("OptionsTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.OptionsTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.OptionsTab)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 432, 161))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBoxHUD = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBoxHUD.setChecked(False)
        self.checkBoxHUD.setTristate(False)
        self.checkBoxHUD.setObjectName("checkBoxHUD")
        self.verticalLayout_3.addWidget(self.checkBoxHUD)
        self.checkBoxUseMercator = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBoxUseMercator.setChecked(False)
        self.checkBoxUseMercator.setTristate(False)
        self.checkBoxUseMercator.setObjectName("checkBoxUseMercator")
        self.verticalLayout_3.addWidget(self.checkBoxUseMercator)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.maxZoomlevelSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.maxZoomlevelSpinBox.setKeyboardTracking(False)
        self.maxZoomlevelSpinBox.setMinimum(0)
        self.maxZoomlevelSpinBox.setMaximum(30)
        self.maxZoomlevelSpinBox.setProperty("value", 18)
        self.maxZoomlevelSpinBox.setObjectName("maxZoomlevelSpinBox")
        self.gridLayout.addWidget(self.maxZoomlevelSpinBox, 1, 1, 1, 1)
        self.maxZoomlevelLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.maxZoomlevelLabel.setObjectName("maxZoomlevelLabel")
        self.gridLayout.addWidget(self.maxZoomlevelLabel, 1, 0, 1, 1)
        self.minZoomlevelLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.minZoomlevelLabel.setObjectName("minZoomlevelLabel")
        self.gridLayout.addWidget(self.minZoomlevelLabel, 0, 0, 1, 1)
        self.dpiLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.dpiLabel.setObjectName("dpiLabel")
        self.gridLayout.addWidget(self.dpiLabel, 2, 0, 1, 1)
        self.minZoomlevelSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.minZoomlevelSpinBox.setKeyboardTracking(False)
        self.minZoomlevelSpinBox.setMinimum(0)
        self.minZoomlevelSpinBox.setMaximum(30)
        self.minZoomlevelSpinBox.setObjectName("minZoomlevelSpinBox")
        self.gridLayout.addWidget(self.minZoomlevelSpinBox, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dpiSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.dpiSpinBox.setEnabled(False)
        self.dpiSpinBox.setKeyboardTracking(False)
        self.dpiSpinBox.setMinimum(72)
        self.dpiSpinBox.setMaximum(768)
        self.dpiSpinBox.setSingleStep(2)
        self.dpiSpinBox.setProperty("value", 96)
        self.dpiSpinBox.setObjectName("dpiSpinBox")
        self.horizontalLayout.addWidget(self.dpiSpinBox)
        self.toggleDpiToolButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/toggleDpiToolButton.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggleDpiToolButton.setIcon(icon5)
        self.toggleDpiToolButton.setCheckable(True)
        self.toggleDpiToolButton.setObjectName("toggleDpiToolButton")
        self.horizontalLayout.addWidget(self.toggleDpiToolButton)
        self.resetDpiToolButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.resetDpiToolButton.setIcon(icon3)
        self.resetDpiToolButton.setCheckable(False)
        self.resetDpiToolButton.setObjectName("resetDpiToolButton")
        self.horizontalLayout.addWidget(self.resetDpiToolButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.OptionsTab, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        TileMapScaleLevelsDockWidget.setWidget(self.dockWidgetContents)
        self.actionHUD = QtWidgets.QAction(TileMapScaleLevelsDockWidget)
        self.actionHUD.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/actionHUD.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHUD.setIcon(icon6)
        self.actionHUD.setObjectName("actionHUD")
        self.actionTMS = QtWidgets.QAction(TileMapScaleLevelsDockWidget)
        self.actionTMS.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/actionTMS.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTMS.setIcon(icon7)
        self.actionTMS.setObjectName("actionTMS")
        self.actionLayers = QtWidgets.QAction(TileMapScaleLevelsDockWidget)
        self.actionLayers.setIcon(icon1)
        self.actionLayers.setObjectName("actionLayers")

        self.retranslateUi(TileMapScaleLevelsDockWidget)
        self.tabWidget.setCurrentIndex(0)
        self.toggleDpiToolButton.toggled['bool'].connect(self.dpiSpinBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(TileMapScaleLevelsDockWidget)

    def retranslateUi(self, TileMapScaleLevelsDockWidget):
        _translate = QtCore.QCoreApplication.translate
        TileMapScaleLevelsDockWidget.setWindowTitle(_translate("TileMapScaleLevelsDockWidget", "Tile Map Scale Levels"))
        self.toolButtonIsActive.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Enable/Disable Scale Levels"))
        self.toolButtonIsActive.setStatusTip(_translate("TileMapScaleLevelsDockWidget", "Enable/Disable Scale Levels"))
        self.toolButtonIsActive.setText(_translate("TileMapScaleLevelsDockWidget", "o"))
        self.toolButtonLayers.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Add Layers"))
        self.toolButtonLayers.setStatusTip(_translate("TileMapScaleLevelsDockWidget", "Add Layers"))
        self.toolButtonLayers.setText(_translate("TileMapScaleLevelsDockWidget", "≡"))
        self.buttonLoadUserDataset.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Add new dataset"))
        self.buttonLoadUserDataset.setStatusTip(_translate("TileMapScaleLevelsDockWidget", "Add new dataset"))
        self.buttonLoadUserDataset.setText(_translate("TileMapScaleLevelsDockWidget", "OSM"))
        self.buttonLoadRefreshUserDatasets.setToolTip(_translate("TileMapScaleLevelsDockWidget", "refresh list of datasets"))
        self.buttonLoadRefreshUserDatasets.setStatusTip(_translate("TileMapScaleLevelsDockWidget", "refresh list of datasets"))
        self.buttonLoadRefreshUserDatasets.setText(_translate("TileMapScaleLevelsDockWidget", "OSM"))
        self.buttonInfo.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Show information"))
        self.buttonInfo.setStatusTip(_translate("TileMapScaleLevelsDockWidget", "Show information"))
        self.buttonInfo.setText(_translate("TileMapScaleLevelsDockWidget", "OSM"))
        self.groupBoxZoomlevels.setTitle(_translate("TileMapScaleLevelsDockWidget", "Zoomlevel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TileMapScaleLevelsDockWidget", "Tool"))
        self.checkBoxHUD.setText(_translate("TileMapScaleLevelsDockWidget", "Show Head-up display"))
        self.checkBoxUseMercator.setText(_translate("TileMapScaleLevelsDockWidget", "Use World Mercator System"))
        self.maxZoomlevelLabel.setText(_translate("TileMapScaleLevelsDockWidget", "max Zoomlevel"))
        self.minZoomlevelLabel.setText(_translate("TileMapScaleLevelsDockWidget", "min Zoomlevel"))
        self.dpiLabel.setText(_translate("TileMapScaleLevelsDockWidget", "DPI"))
        self.toggleDpiToolButton.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Allow to set dpi directly"))
        self.toggleDpiToolButton.setText(_translate("TileMapScaleLevelsDockWidget", "..."))
        self.resetDpiToolButton.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Reset DPI"))
        self.resetDpiToolButton.setText(_translate("TileMapScaleLevelsDockWidget", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OptionsTab), _translate("TileMapScaleLevelsDockWidget", "Options"))
        self.actionHUD.setText(_translate("TileMapScaleLevelsDockWidget", "Head-up display"))
        self.actionHUD.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Head-up display"))
        self.actionTMS.setText(_translate("TileMapScaleLevelsDockWidget", "TMS Widget"))
        self.actionTMS.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Plugin widget"))
        self.actionLayers.setText(_translate("TileMapScaleLevelsDockWidget", "Layers"))
        self.actionLayers.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Add Layer"))

from . import resources_rc
