# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tilemapscalelevelswidget.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TileMapScaleLevelsDockWidget(object):
    def setupUi(self, TileMapScaleLevelsDockWidget):
        TileMapScaleLevelsDockWidget.setObjectName("TileMapScaleLevelsDockWidget")
        TileMapScaleLevelsDockWidget.resize(789, 339)
        TileMapScaleLevelsDockWidget.setMinimumSize(QtCore.QSize(286, 314))
        TileMapScaleLevelsDockWidget.setMaximumSize(QtCore.QSize(524287, 524287))
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBoxDatasets = QtWidgets.QGroupBox(self.tab)
        self.groupBoxDatasets.setObjectName("groupBoxDatasets")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxDatasets)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBoxUserDatasets = QtWidgets.QComboBox(self.groupBoxDatasets)
        self.comboBoxUserDatasets.setObjectName("comboBoxUserDatasets")
        self.horizontalLayout_2.addWidget(self.comboBoxUserDatasets)
        self.buttonLoadUserDataset = QtWidgets.QToolButton(self.groupBoxDatasets)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonLoadUserDataset.setIcon(icon)
        self.buttonLoadUserDataset.setIconSize(QtCore.QSize(22, 22))
        self.buttonLoadUserDataset.setObjectName("buttonLoadUserDataset")
        self.horizontalLayout_2.addWidget(self.buttonLoadUserDataset)
        self.buttonLoadRefreshUserDatasets = QtWidgets.QToolButton(self.groupBoxDatasets)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/view-refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonLoadRefreshUserDatasets.setIcon(icon1)
        self.buttonLoadRefreshUserDatasets.setIconSize(QtCore.QSize(22, 22))
        self.buttonLoadRefreshUserDatasets.setObjectName("buttonLoadRefreshUserDatasets")
        self.horizontalLayout_2.addWidget(self.buttonLoadRefreshUserDatasets)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBoxDatasets)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxIsActive = QtWidgets.QCheckBox(self.tab)
        self.checkBoxIsActive.setChecked(True)
        self.checkBoxIsActive.setTristate(False)
        self.checkBoxIsActive.setObjectName("checkBoxIsActive")
        self.horizontalLayout.addWidget(self.checkBoxIsActive)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonInfo = QtWidgets.QToolButton(self.tab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/help-about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonInfo.setIcon(icon2)
        self.buttonInfo.setIconSize(QtCore.QSize(22, 22))
        self.buttonInfo.setObjectName("buttonInfo")
        self.horizontalLayout.addWidget(self.buttonInfo)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.sliderZoomlevels = QtWidgets.QSlider(self.groupBox)
        self.sliderZoomlevels.setToolTip("")
        self.sliderZoomlevels.setStatusTip("")
        self.sliderZoomlevels.setMaximum(25)
        self.sliderZoomlevels.setSliderPosition(0)
        self.sliderZoomlevels.setOrientation(QtCore.Qt.Horizontal)
        self.sliderZoomlevels.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.sliderZoomlevels.setTickInterval(0)
        self.sliderZoomlevels.setObjectName("sliderZoomlevels")
        self.verticalLayout.addWidget(self.sliderZoomlevels)
        self.spinBoxZoomlevels = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxZoomlevels.setKeyboardTracking(False)
        self.spinBoxZoomlevels.setMaximum(25)
        self.spinBoxZoomlevels.setObjectName("spinBoxZoomlevels")
        self.verticalLayout.addWidget(self.spinBoxZoomlevels)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab, "")
        self.OptionsTab = QtWidgets.QWidget()
        self.OptionsTab.setObjectName("OptionsTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.OptionsTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBoxUseMercator = QtWidgets.QCheckBox(self.OptionsTab)
        self.checkBoxUseMercator.setChecked(False)
        self.checkBoxUseMercator.setTristate(False)
        self.checkBoxUseMercator.setObjectName("checkBoxUseMercator")
        self.verticalLayout_5.addWidget(self.checkBoxUseMercator)
        self.checkBoxUseOnTheFlyTransformation = QtWidgets.QCheckBox(self.OptionsTab)
        self.checkBoxUseOnTheFlyTransformation.setChecked(False)
        self.checkBoxUseOnTheFlyTransformation.setTristate(False)
        self.checkBoxUseOnTheFlyTransformation.setObjectName("checkBoxUseOnTheFlyTransformation")
        self.verticalLayout_5.addWidget(self.checkBoxUseOnTheFlyTransformation)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.maxZoomlevelSpinBox = QtWidgets.QSpinBox(self.OptionsTab)
        self.maxZoomlevelSpinBox.setKeyboardTracking(False)
        self.maxZoomlevelSpinBox.setMinimum(-10)
        self.maxZoomlevelSpinBox.setMaximum(30)
        self.maxZoomlevelSpinBox.setProperty("value", 18)
        self.maxZoomlevelSpinBox.setObjectName("maxZoomlevelSpinBox")
        self.gridLayout.addWidget(self.maxZoomlevelSpinBox, 1, 1, 1, 1)
        self.dpiSpinBox = QtWidgets.QSpinBox(self.OptionsTab)
        self.dpiSpinBox.setEnabled(False)
        self.dpiSpinBox.setKeyboardTracking(False)
        self.dpiSpinBox.setMinimum(72)
        self.dpiSpinBox.setMaximum(768)
        self.dpiSpinBox.setSingleStep(2)
        self.dpiSpinBox.setProperty("value", 96)
        self.dpiSpinBox.setObjectName("dpiSpinBox")
        self.gridLayout.addWidget(self.dpiSpinBox, 2, 1, 1, 1)
        self.maxZoomlevelLabel = QtWidgets.QLabel(self.OptionsTab)
        self.maxZoomlevelLabel.setObjectName("maxZoomlevelLabel")
        self.gridLayout.addWidget(self.maxZoomlevelLabel, 1, 0, 1, 1)
        self.minZoomlevelLabel = QtWidgets.QLabel(self.OptionsTab)
        self.minZoomlevelLabel.setObjectName("minZoomlevelLabel")
        self.gridLayout.addWidget(self.minZoomlevelLabel, 0, 0, 1, 1)
        self.dpiLabel = QtWidgets.QLabel(self.OptionsTab)
        self.dpiLabel.setObjectName("dpiLabel")
        self.gridLayout.addWidget(self.dpiLabel, 2, 0, 1, 1)
        self.minZoomlevelSpinBox = QtWidgets.QSpinBox(self.OptionsTab)
        self.minZoomlevelSpinBox.setKeyboardTracking(False)
        self.minZoomlevelSpinBox.setMinimum(-10)
        self.minZoomlevelSpinBox.setMaximum(30)
        self.minZoomlevelSpinBox.setObjectName("minZoomlevelSpinBox")
        self.gridLayout.addWidget(self.minZoomlevelSpinBox, 0, 1, 1, 1)
        self.toggleDpiToolButton = QtWidgets.QToolButton(self.OptionsTab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/draw-freehand.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggleDpiToolButton.setIcon(icon3)
        self.toggleDpiToolButton.setCheckable(True)
        self.toggleDpiToolButton.setObjectName("toggleDpiToolButton")
        self.gridLayout.addWidget(self.toggleDpiToolButton, 2, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.tabWidget.addTab(self.OptionsTab, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        TileMapScaleLevelsDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(TileMapScaleLevelsDockWidget)
        self.tabWidget.setCurrentIndex(0)
        self.toggleDpiToolButton.toggled['bool'].connect(self.dpiSpinBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(TileMapScaleLevelsDockWidget)

    def retranslateUi(self, TileMapScaleLevelsDockWidget):
        _translate = QtCore.QCoreApplication.translate
        TileMapScaleLevelsDockWidget.setWindowTitle(_translate("TileMapScaleLevelsDockWidget", "Tile Map Scale Levels"))
        self.groupBoxDatasets.setTitle(_translate("TileMapScaleLevelsDockWidget", "Datasets"))
        self.buttonLoadUserDataset.setToolTip(_translate("TileMapScaleLevelsDockWidget", "load selected dataset"))
        self.buttonLoadUserDataset.setStatusTip(_translate("TileMapScaleLevelsDockWidget", "load selected dataset"))
        self.buttonLoadUserDataset.setText(_translate("TileMapScaleLevelsDockWidget", "OSM"))
        self.buttonLoadRefreshUserDatasets.setToolTip(_translate("TileMapScaleLevelsDockWidget", "refresh list of datasets"))
        self.buttonLoadRefreshUserDatasets.setStatusTip(_translate("TileMapScaleLevelsDockWidget", "refresh list of datasets"))
        self.buttonLoadRefreshUserDatasets.setText(_translate("TileMapScaleLevelsDockWidget", "OSM"))
        self.checkBoxIsActive.setText(_translate("TileMapScaleLevelsDockWidget", "activate zoomlevels"))
        self.buttonInfo.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Show information"))
        self.buttonInfo.setStatusTip(_translate("TileMapScaleLevelsDockWidget", "Show information"))
        self.buttonInfo.setText(_translate("TileMapScaleLevelsDockWidget", "OSM"))
        self.groupBox.setTitle(_translate("TileMapScaleLevelsDockWidget", "Zoomlevel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TileMapScaleLevelsDockWidget", "Tool"))
        self.checkBoxUseMercator.setText(_translate("TileMapScaleLevelsDockWidget", "Use World Mercator System"))
        self.checkBoxUseOnTheFlyTransformation.setText(_translate("TileMapScaleLevelsDockWidget", "Use \'On-The-Fly\' Transformation"))
        self.maxZoomlevelLabel.setText(_translate("TileMapScaleLevelsDockWidget", "max Zoomlevel"))
        self.minZoomlevelLabel.setText(_translate("TileMapScaleLevelsDockWidget", "min Zoomlevel"))
        self.dpiLabel.setText(_translate("TileMapScaleLevelsDockWidget", "DPI"))
        self.toggleDpiToolButton.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Allow to set dpi directly"))
        self.toggleDpiToolButton.setText(_translate("TileMapScaleLevelsDockWidget", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OptionsTab), _translate("TileMapScaleLevelsDockWidget", "Options"))

from . import resources_rc
